server:
  port: 8081

fiap:
  debug: true

spring:
  datasource:
    url: jdbc:h2:~/fiapsongdb;DB_CLOSE_ON_EXIT=FALSE
    password: fiap
    username: fiap
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
